# Generated by Django 5.2.7 on 2025-10-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='expence',
            table='expence',
        ),
        migrations.AlterModelTable(
            name='income',
            table='income',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
