# Generated by Django 5.2.7 on 2025-10-13 14:11

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def dedupe_user_credentials(apps, schema_editor):
    User = apps.get_model("myapp", "User")
    existing_names = set()
    for user in User.objects.order_by("id"):
        current_name = user.uname or ""
        target_name = current_name
        if target_name in existing_names:
            suffix = 1
            while True:
                candidate = f"{current_name}_{suffix}"
                if candidate not in existing_names:
                    target_name = candidate
                    break
                suffix += 1
        existing_names.add(target_name)
        updated_fields = []
        if target_name != current_name:
            user.uname = target_name
            updated_fields.append("uname")

        password = user.upassword or ""
        if password and not password.startswith("pbkdf2_"):
            user.upassword = make_password(password)
            updated_fields.append("upassword")

        if updated_fields:
            user.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_monthly_budget_alter_expence_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='upassword',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(dedupe_user_credentials, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
